name: CI

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3.5.0

      - name: Run readme update script
        run: |
          npm install
          node index.js
          git diff -s --exit-code README.md
          status=$?
          if [[ $status -eq 1 ]]; then
            echo "Please run `node index.js` & commit all changes to README.md"
            exit 1
          fi
